###########
# Classifier #
###########

image_dir: './data/CelebA/images/'
image_label_dict: './data/CelebA/YSBBB_classification.txt'


log_dir: './output/classifier'
name: 'CelebA-YSBBB'

num_channel: 3
num_class: 5
input_size: 128
batch_size: 32
epochs: 5
ckpt_dir_continue: ''
